"""
Tests for the static-site exporter (docflow.core.site_exporter).
"""

import json
import os

import pytest

from docflow.core.site_exporter import (
    collect_units,
    convert_github_callouts,
    export_site,
    parse_frontmatter,
    validate_out_path,
)


def _write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


@pytest.fixture
def docs_repo(tmp_path):
    root = tmp_path / "docs"
    _write(
        str(root / "architecture" / "index.md"),
        """---
title: "Architecture"
description: "System overview."
type: "architecture"
status: "stable"
last_updated: "2026-08-22T00:00:00Z"
tags: ["overview", "system"]
---

# Architecture

> [!NOTE]
> Generated by DocFlow.

```mermaid
graph TD; A-->B;
```
""",
    )
    _write(
        str(root / "features" / "auth" / "index.md"),
        """---
title: "Auth"
description: "Login and sessions."
tags: ["auth"]
status: "stable"
---

# Auth
""",
    )
    _write(
        str(root / "features" / "auth" / "context.json"),
        '{"feature": "auth"}',
    )
    _write(str(root / "features" / "auth" / "files.md"), "# Files\n")
    _write(str(root / "routes" / "api" / "index.md"), "---\ntitle: API\n---\n# API\n")
    _write(str(root / ".docflow" / "config.yml"), "project:\n  name: t\n")
    return str(root)


def test_parse_frontmatter_splits_yaml_and_body():
    fm, body = parse_frontmatter("---\ntitle: X\n---\n\nBody here\n")
    assert fm == {"title": "X"}
    assert body == "Body here\n"


def test_convert_github_callouts_to_admonitions():
    converted = convert_github_callouts("> [!NOTE]\n> line one\n> line two\n")
    assert ":::note" in converted
    assert ":::" in converted
    assert "[!NOTE]" not in converted
    assert "line one" in converted and "line two" in converted


def test_collect_units_walks_types_and_skips_machine_files(docs_repo):
    units = collect_units(docs_repo)
    names = {(u.doc_type, u.name) for u in units}
    assert ("architecture", "architecture") in names
    assert ("features", "auth") in names
    assert ("routes", "api") in names
    assert all(u.name != ".docflow" for u in units)
    auth = next(u for u in units if (u.doc_type, u.name) == ("features", "auth"))
    assert auth.frontmatter.get("title") == "Auth"


def test_export_writes_docusaurus_tree(docs_repo, tmp_path):
    out = str(tmp_path / "site")
    result = export_site(docs_repo, out)

    assert result.pages == 3
    arch = os.path.join(out, "docs", "architecture.md")
    auth = os.path.join(out, "docs", "features", "auth.md")
    api = os.path.join(out, "docs", "routes", "api.md")
    for path in (arch, auth, api):
        assert os.path.isfile(path)

    with open(arch) as fh:
        text = fh.read()
    assert "sidebar_position: 0" in text
    assert "keywords:" in text and "- overview" in text
    assert ":::note" in text and "[!NOTE]" not in text
    assert "graph TD" in text

    category_path = os.path.join(out, "docs", "features", "_category_.json")
    with open(category_path) as fh:
        category = json.load(fh)
    assert category["label"] == "Features"

    for machine in ("context.json", "files.md"):
        assert not os.path.exists(os.path.join(out, "docs", "features", "auth", machine))
    assert not os.path.exists(os.path.join(out, "docs", ".docflow"))


def test_export_rejects_output_inside_docs_repo(docs_repo):
    with pytest.raises(ValueError, match="inside the docs repo"):
        export_site(docs_repo, os.path.join(docs_repo, "site"))
    with pytest.raises(ValueError):
        export_site(docs_repo, docs_repo)


def test_export_rejects_unknown_format(docs_repo, tmp_path):
    with pytest.raises(ValueError, match="Unsupported export format"):
        export_site(docs_repo, str(tmp_path / "out"), fmt="hugo")


def test_export_empty_docs_repo_raises(tmp_path):
    empty = tmp_path / "empty"
    empty.mkdir()
    with pytest.raises(ValueError, match="No documentation pages"):
        export_site(str(empty), str(tmp_path / "out"))


def test_validate_out_path_allows_sibling():
    validate_out_path("/tmp/repo", "/tmp/repo-site")


def test_unit_pages_get_sequential_sidebar_positions(docs_repo):
    out = str(docs_repo + "-site")
    export_site(docs_repo, out)
    auth = os.path.join(out, "docs", "features", "auth.md")
    with open(auth) as fh:
        assert "sidebar_position: 1" in fh.read()


def test_extra_frontmatter_keys_pass_through(docs_repo, tmp_path):
    out = str(docs_repo + "-site")
    export_site(docs_repo, out)
    with open(os.path.join(out, "docs", "architecture.md")) as fh:
        text = fh.read()
    assert 'status: stable' in text
    assert "last_updated" in text
    assert "keywords:" in text
    assert "- overview" in text


def test_callout_with_inline_title_and_plain_quotes_untouched():
    converted = convert_github_callouts(
        "> [!TIP] pro tip\n> body\n\n> plain quote stays\n"
    )
    assert ":::tip" in converted
    assert "pro tip" in converted
    assert "[!TIP]" not in converted
    assert "> plain quote stays" in converted


def test_collect_units_ignores_root_files_and_hidden_dirs(docs_repo):
    _write(os.path.join(docs_repo, "README.md"), "# not a unit\n")
    _write(os.path.join(docs_repo, ".hidden", "index.md"), "# nope\n")
    units = collect_units(docs_repo)
    names = {u.name for u in units}
    assert "README.md" not in names
    assert all(not n.startswith(".") for n in names)


def test_export_reports_progress(docs_repo, tmp_path):
    events = []
    export_site(docs_repo, str(tmp_path / "out"), on_progress=events.append)
    assert any("Exported 3 page(s)" in e for e in events)


def test_validate_out_path_rejects_relative_inside_path(docs_repo, monkeypatch):
    monkeypatch.chdir(docs_repo)
    with pytest.raises(ValueError, match="inside"):
        validate_out_path(".", "./sub")
